# Generated by Django 2.2.6 on 2019-12-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=10)),
                ('email_of_user', models.CharField(max_length=50)),
                ('message_of_user', models.TextField()),
            ],
        ),
    ]
