# Generated by Django 2.2.6 on 2019-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webFinal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_of_car', models.CharField(max_length=100)),
                ('volume', models.IntegerField()),
                ('type_of_drive', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=100)),
                ('carcase', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
